language: ruby
sudo: false
cache: bundler
rvm:
  - 2.3.0
script: bundle exec rspec
before_install:
  - gem update --system
  - gem update bundler
services:
  - redis-server
notifications:
  email: false
  webhooks:
    urls:
      - https://util.perceptes.com:8080/travis
